name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  check-lint-and-run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Check linter
        run: npm run lint
      - name: Run tests
        run: npm test
